// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiversideFishhut.API.Data;

#nullable disable

namespace RiversideFishhut.API.Migrations
{
    [DbContext(typeof(RiversideFishhutDbContext))]
    [Migration("20230329153749_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RiversideFishhut.API.Data.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("AdminEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("RoleId");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AdminEmailAddress = "Admin@gmail.com",
                            AdminName = "Admin",
                            AdminPassword = "Admin123",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.BusinessHour", b =>
                {
                    b.Property<int>("BusinessHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessHourId"), 1L, 1);

                    b.Property<string>("BusinessTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessHourId");

                    b.ToTable("businessHours");

                    b.HasData(
                        new
                        {
                            BusinessHourId = 1,
                            BusinessTime = "Closed",
                            DayOfWeek = "Monday"
                        },
                        new
                        {
                            BusinessHourId = 2,
                            BusinessTime = "09:00 - 17:00",
                            DayOfWeek = "Tuesday"
                        },
                        new
                        {
                            BusinessHourId = 3,
                            BusinessTime = "09:00 - 17:00",
                            DayOfWeek = "Wednesday"
                        },
                        new
                        {
                            BusinessHourId = 4,
                            BusinessTime = "09:00 - 17:00",
                            DayOfWeek = "Thursday"
                        },
                        new
                        {
                            BusinessHourId = 5,
                            BusinessTime = "09:00 - 17:00",
                            DayOfWeek = "Friday"
                        },
                        new
                        {
                            BusinessHourId = 6,
                            BusinessTime = "09:00 - 17:00",
                            DayOfWeek = "Saturday"
                        },
                        new
                        {
                            BusinessHourId = 7,
                            BusinessTime = "Closed",
                            DayOfWeek = "Sunday"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Main Dish",
                            Name = "2 PC Dinner"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.FoodType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("foodTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Description = "This type is for 2 Pc fish with 1 pack chip.",
                            TypeName = "2 PC Dinner"
                        },
                        new
                        {
                            TypeId = 2,
                            Description = "This is fish.",
                            TypeName = "Fish "
                        },
                        new
                        {
                            TypeId = 3,
                            Description = "This product has discount right now.",
                            TypeName = "Deal"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<decimal>("BeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("table")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("StaffId");

                    b.ToTable("order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9284),
                            OrderStatusId = 1,
                            OrderTypeId = 1,
                            PaymentStatus = false,
                            StaffId = 1,
                            Tax = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            OrderId = 2,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9307),
                            OrderStatusId = 4,
                            OrderTypeId = 2,
                            PaymentStatus = true,
                            StaffId = 2,
                            Tax = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            OrderId = 3,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9308),
                            OrderStatusId = 2,
                            OrderTypeId = 1,
                            PaymentStatus = false,
                            StaffId = 1,
                            Tax = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            OrderId = 4,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9310),
                            OrderStatusId = 1,
                            OrderTypeId = 1,
                            PaymentStatus = false,
                            StaffId = 1,
                            Tax = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            OrderId = 5,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9312),
                            OrderStatusId = 1,
                            OrderTypeId = 1,
                            PaymentStatus = false,
                            StaffId = 1,
                            Tax = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            OrderId = 6,
                            BeforeTax = 0m,
                            OrderDate = new DateTime(2023, 3, 29, 11, 37, 49, 95, DateTimeKind.Local).AddTicks(9313),
                            OrderStatusId = 2,
                            OrderTypeId = 3,
                            PaymentStatus = true,
                            StaffId = 2,
                            Tax = 0m,
                            TotalCost = 0m
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.OrderLineItem", b =>
                {
                    b.Property<int>("OrderLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineItemId"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderLineItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("orderLineItem");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusId"), 1L, 1);

                    b.Property<string>("OrderStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("orderStatus");

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            OrderStatusName = "Ordered"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            OrderStatusName = "In Progress"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            OrderStatusName = "Ready"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            OrderStatusName = "Complete"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.OrderType", b =>
                {
                    b.Property<int>("OrderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderTypeId"), 1L, 1);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderTypeId");

                    b.ToTable("orderType");

                    b.HasData(
                        new
                        {
                            OrderTypeId = 1,
                            TypeName = "Dine In"
                        },
                        new
                        {
                            OrderTypeId = 2,
                            TypeName = "Take Out"
                        },
                        new
                        {
                            OrderTypeId = 3,
                            TypeName = "Phone Order"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("AltName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dine_in_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Take_out_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AltName = "2 PC W/C",
                            CategoryId = 1,
                            Description = "Description",
                            Dine_in_price = 10m,
                            ProductName = "2Pc Whitefish & Chips",
                            Take_out_price = 9m
                        },
                        new
                        {
                            ProductId = 2,
                            AltName = "2 PC COD/C",
                            CategoryId = 1,
                            Description = "Description",
                            Dine_in_price = 12m,
                            ProductName = "2Pc Cod & Chips",
                            Take_out_price = 11m
                        },
                        new
                        {
                            ProductId = 3,
                            AltName = "2 PC HDK/C",
                            CategoryId = 1,
                            Description = "Description",
                            Dine_in_price = 14m,
                            ProductName = "2Pc Haddock & Chips",
                            Take_out_price = 13m
                        },
                        new
                        {
                            ProductId = 4,
                            AltName = "2PC HB/C",
                            CategoryId = 1,
                            Description = "Description",
                            Dine_in_price = 16m,
                            ProductName = "2Pc Halibut & Chips",
                            Take_out_price = 15m
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.ProductFoodType", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("productFoodTypes");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            TypeId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            TypeId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            TypeId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            TypeId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            TypeId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            TypeId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            TypeId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            TypeId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            TypeId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            TypeId = 3
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleDescription = "Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleDescription = "Staff member",
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.HasIndex("RoleId");

                    b.ToTable("staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Description = "description1",
                            Password = "Password1",
                            RoleId = 1,
                            StaffName = "Staff 1"
                        },
                        new
                        {
                            StaffId = 2,
                            Description = "description2",
                            Password = "Password2",
                            RoleId = 2,
                            StaffName = "Staff 2"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.WebsiteInfo", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineOrderLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoId");

                    b.ToTable("websiteInfos");

                    b.HasData(
                        new
                        {
                            InfoId = 1,
                            Address = "157 king st west Cambridge, ON, N3H 1B5",
                            Description = "This cozy restaurant specializes in traditional English fish and French fries, serving up freshly fried, crispy and flavorful fish sourced from local suppliers, and thick golden fries that make the perfect side dish.",
                            LogoImage = "Logo name",
                            OnlineOrderLink = "https://www.skipthedishes.com/riverside-fish-hut?utm_source=riversidefishhutmenu.ca&utm_medium=microsites&utm_campaign=microsites",
                            PhoneNumber = "519-653-0788",
                            StoreName = "Riverside Fishhut"
                        });
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Admin", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.FoodType", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Product", null)
                        .WithMany("FoodTypes")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Order", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiversideFishhut.API.Data.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.OrderLineItem", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Product", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.ProductFoodType", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Product", "Product")
                        .WithMany("ProductFoodTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RiversideFishhut.API.Data.FoodType", "FoodType")
                        .WithMany("ProductFoodTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoodType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Staff", b =>
                {
                    b.HasOne("RiversideFishhut.API.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.FoodType", b =>
                {
                    b.Navigation("ProductFoodTypes");
                });

            modelBuilder.Entity("RiversideFishhut.API.Data.Product", b =>
                {
                    b.Navigation("FoodTypes");

                    b.Navigation("ProductFoodTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
